### ISSUE TITLE
Missing python packages

### ISSUE THREAD

**Issue by kaajjaak** [cdurau/Treehouse-Downloader#3]
I'm getting this error when running the program:
$ python treehouse.py
Searching for Downloads...
Traceback (most recent call last):
  File "E:\TeamTreeHouse\Treehouse-Downloader-master\treehouse.py", line 71, in <module>
    main()
  File "E:\TeamTreeHouse\Treehouse-Downloader-master\treehouse.py", line 16, in main
    settings = get_settings()
  File "E:\TeamTreeHouse\Treehouse-Downloader-master\modules\helper.py", line 53, in get_settings
    settings = json.load(f)
  File "C:\Users\Jaak\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Jaak\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Jaak\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jaak\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 5 column 25 (char 126)

also I had to delete the ==4.4.1 from requirements.txt because this specific version wouldn't install, I hope that isn't the problem though

**Comment by cdurau** [comment]
If you're on Linux try before installing lxml:
`sudo apt-get install libxml2-dev libxslt1-dev -y`

I suggest to install the specific versions because these are testet and running.
Of course you can try to update the packages by yourself and look if everything is still working.

**Comment by kaajjaak** [comment]
I'm not on Linux but I'll try it in a vm

**Comment by kaajjaak** [comment]
I tried it in a linux vm using the correct version but I'm still getting the same errors, ill try some more but is it possible that the program doesn't work anymore? If you don't have an account for testing, I don't mind sending you mine

**Comment by kaajjaak** [comment]
actually nvm I think I fixed it

**Comment by cedric89** [comment]
I tried it just now with a new cloned version and Python 3.9 venv. Everything is working as expected. 

The error message suggests that there might be a formatting error within your settings.json or the json package from python itself.

Please don‘t post your settings file here because of your password.

Can you try to install it in a venv like:
`
python -m venv venv
venv/bin/activate
pip install -r requirements.txt
python treehouse.py
`

I will test it with windows when I find time.

**Comment by cedric89** [comment]
> actually nvm I think I fixed it

 Can you tell us what went wrong if somebody gets the same error message?

**Comment by kaajjaak** [comment]
Downloading Video: 05. Adding Changes to a Project on GitHub.webm

Traceback (most recent call last):

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/treehouse.py", line 71, in <module>

    main()

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/treehouse.py", line 50, in main

    workshop.start_download()

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/types/workshop.py", line 161, in start_download

    download_steps(driver, self.steps, self.root, self.dir)

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/download_helper.py", line 21, in download_steps

    instruction.start_download(step_no, target)

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/types/instruction.py", line 117, in start_download

    self.get_meta()

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/types/instruction.py", line 53, in get_meta

    paragraph.text = transform_links(c)

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/helper.py", line 152, in transform_links

    href = link['href']

  File "/usr/local/lib/python3.9/dist-packages/bs4/element.py", line 1016, in __getitem__

    return self.attrs[key]

KeyError: 'href'


im getting this error it downloaded a couple files though

**Comment by kaajjaak** [comment]
> > actually nvm I think I fixed it
> 
> Can you tell us what went wrong if somebody gets the same error message?

im not entirely sure, I just redownloaded the files and it worked

**Comment by kaajjaak** [comment]
im getting this error using the venv command, do I need to install something for it first? I don't have much experience using linux
osboxes@osboxes:~/Downloads/folder/Treehouse-Downloader-master$ python3 -m venv venv venv/bin/activate pip install -r requirements.txt python3 treehouse.py

usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip] [--prompt PROMPT] [--upgrade-deps] ENV_DIR [ENV_DIR ...]

venv: error: unrecognized arguments: -r requirements.txt python3 treehouse.py

**Comment by kaajjaak** [comment]
this is from the course python basics 3 if I understand correctly

**Comment by kaajjaak** [comment]
also I wasn't going to send my password in here but I can send it to you via email/social media or something like that

**Comment by kaajjaak** [comment]
> this is from the course python basics 3 if I understand correctly
its in the python techdegree

**Comment by cedric89** [comment]
> im getting this error using the venv command, do I need to install something for it first? I don't have much experience using linux osboxes@osboxes:~/Downloads/folder/Treehouse-Downloader-master$ python3 -m venv venv venv/bin/activate pip install -r requirements.txt python3 treehouse.py
> 
> usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip] [--prompt PROMPT] [--upgrade-deps] ENV_DIR [ENV_DIR ...]
> 
> venv: error: unrecognized arguments: -r requirements.txt python3 treehouse.py

I posted the venv command for windows, sorry.

For Linux it is:
`source venv/bin/activate`

It is a virtual environment where you can safeley test your packages and python commands with specific versions. You don‘t need to use a virtual environment if you want to install all packages globally.

**Comment by kaajjaak** [comment]
i'll try it but if I understand it correctly, it probably won't solve the new error I'm getting right?

**Comment by cedric89** [comment]
> also I wasn't going to send my password in here but I can send it to you via email/social media or something like that

Thank you very much,  but I still have an active membership for treehouse. 🙂 I just thought that there might be a special character in your download path or other settings if the error comes up. Maybe it was some char in the course title which is not allowed in windows folder paths. 

 But I‘m happy if you were able to fix it! 🙂

**Comment by cedric89** [comment]
> i'll try it but if I understand it correctly, it probably won't solve the new error I'm getting right?

The new error just says these are the wrong options for the venv command, because they are different for linux. Try the one with source.

**Comment by kaajjaak** [comment]
I'm still getting this error:
`Downloading Instructions: The Random Library.md

Downloading Instructions: How to Battle Imposter Syndrome.md

Share Your Techdegree Projects With GitHub Desktop

Traceback (most recent call last):

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/treehouse.py", line 71, in <module>

    main()

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/treehouse.py", line 50, in main

    workshop.start_download()

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/types/workshop.py", line 161, in start_download

    download_steps(driver, self.steps, self.root, self.dir)

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/download_helper.py", line 21, in download_steps

    instruction.start_download(step_no, target)

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/types/instruction.py", line 117, in start_download

    self.get_meta()

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/types/instruction.py", line 53, in get_meta

    paragraph.text = transform_links(c)

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/modules/helper.py", line 152, in transform_links

    href = link['href']

  File "/home/osboxes/Downloads/folder/Treehouse-Downloader-master/venv/lib/python3.9/site-packages/bs4/element.py", line 1016, in __getitem__

    return self.attrs[key]

KeyError: 'href'

`
I'm downloading again in case its the venv thing though

**Comment by kaajjaak** [comment]
I'm not getting this error on the first file, it has already downloaded a couple files when it gives this error, it's not always on the same file either

**Comment by kaajjaak** [comment]
im getting it on this link again: https://teamtreehouse.com/library/share-your-techdegree-projects-with-github-desktop
ill try commenting it in case its just this link that is broken

**Comment by kaajjaak** [comment]
yeah I checked and it always get stuck on this link, maybe this link just doesn't work

**Comment by kaajjaak** [comment]
Could not get page type for: https://teamtreehouse.com/projects/the-number-guessing-game

I'm getting this error, can you not download projects?

**Comment by cedric89** [comment]
> Could not get page type for: https://teamtreehouse.com/projects/the-number-guessing-game
> 
> I'm getting this error, can you not download projects?

No, there were no projects when I first developed this app. Maybe I can add this feature in a future version.

**Comment by cedric89** [comment]
> im getting it on this link again: https://teamtreehouse.com/library/share-your-techdegree-projects-with-github-desktop
> ill try commenting it in case its just this link that is broken

It‘s a techdegree link and not implemented.

**Comment by kaajjaak** [comment]
ah alright, no problem, everything else worked so thats okay! thanks for all the help!

**Comment by kaajjaak** [comment]
also a cool feature would be to number the folders so that you can see in which order the links were provides so you can easily see the order of the files, but no worries if you don't implement this, its already really cool what you made!

**Comment by cdurau** [comment]
> also a cool feature would be to number the folders so that you can see in which order the links were provides so you can easily see the order of the files, but no worries if you don't implement this, its already really cool what you made!

Thank you very much! :-)
The courses should be numbered for every track, also the chapters for every course. Or do you have something else in mind?

**Comment by kaajjaak** [comment]
maybe that when you insert a link that is a exam or a project, it wont stop the program but just give the error message and remind you of the error messages in the end, i redownloaded the same files a couple of times because it had stopped midways

**Comment by cdurau** [comment]
> maybe that when you insert a link that is a exam or a project, it wont stop the program but just give the error message and remind you of the error messages in the end, i redownloaded the same files a couple of times because it had stopped midways

I didn't even know that you can download these types :-D As far as I know I only implemented tracks, courses, workshops, project files and some text types.

**Comment by kaajjaak** [comment]
yeah, you can't download these types, but the problem is when you insert a link that is one of those, it stops the program instead of skipping it, I would like it to skip the link instead or at least make it an optional parameter, its fine if you don't implement it though, its really just aesthetics
